# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ngx-event-hub publish to npm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Setup ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      working-directory: ./ngx-event-hub-lib
      run: |
        rm -rf node_modules package-lock.json
        npm install
    - name: build lib
      working-directory: ./ngx-event-hub-lib
      run: ./node_modules/.bin/ng build
    - name: Set npm registry
      run: npm config set registry https://registry.npmjs.org/
    - name: publish lib
      run: | 
        echo $NODE_AUTH_TOKEN
        npm whoami
      working-directory: ./ngx-event-hub-lib/dist/ngx-event-hub
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
